
# job that downloads the html report from the artifacts and uploads them into vsdrops.
parameters:

- name: runTests
  type: boolean
  default: true

- name: devicePrefix
  type: string 
  default: 'ios' # default context, since we started dealing with iOS devices. 

steps:

- checkout: self
  persistCredentials: true

- template: download-artifacts.yml 
  parameters:
    devicePrefix: ${{ parameters.devicePrefix }}
  enabled: ${{ parameters.runTests }} # no tests, do not download anything

# Upload full report to vsdrops using the the build numer and id as uuids.
- task: ms-vscs-artifact.build-tasks.artifactDropTask-1.artifactDropTask@0
  displayName: 'Publish to Artifact Services Drop'
  enabled: ${{ parameters.runTests }} # no tests, nothing to publish
  inputs:
    dropServiceURI: 'https://devdiv.artifacts.visualstudio.com/DefaultCollection'
    dropMetadataContainerName: 'DropMetadata-${{ parameters.devicePrefix }}'
    buildNumber: 'xamarin-macios/device-tests/$(Build.BuildNumber)/$(Build.BuildId)/${{ parameters.devicePrefix }}'
    sourcePath: $(HTML_REPORT_PATH)
    detailedLog: true
    usePat: true 
